//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMasterSoftWA.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", ConfigurationName="ServicioWS.ProductoraWS")]
    public interface ProductoraWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/ProductoraWS/listarTodasProductorasRe" +
            "quest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/ProductoraWS/listarTodasProductorasRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse listarTodasProductoras(EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/ProductoraWS/listarTodasProductorasRe" +
            "quest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/ProductoraWS/listarTodasProductorasRe" +
            "sponse")]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse> listarTodasProductorasAsync(EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe")]
    public partial class productora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private int idProductoraField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idProductora {
            get {
                return this.idProductoraField;
            }
            set {
                this.idProductoraField = value;
                this.RaisePropertyChanged("idProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private byte[] bannerPromocionalField;
        
        private ushort clasificacionField;
        
        private double costoRealizacionField;
        
        private string descripcionField;
        
        private System.DateTime fechaRealizacionField;
        
        private bool fechaRealizacionFieldSpecified;
        
        private int idEventoField;
        
        private string nombreField;
        
        private bool permiteGrabacionField;
        
        private bool permiteReingresoField;
        
        private productora productoraField;
        
        private tipoEvento tipoEventoField;
        
        private bool tipoEventoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] bannerPromocional {
            get {
                return this.bannerPromocionalField;
            }
            set {
                this.bannerPromocionalField = value;
                this.RaisePropertyChanged("bannerPromocional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ushort clasificacion {
            get {
                return this.clasificacionField;
            }
            set {
                this.clasificacionField = value;
                this.RaisePropertyChanged("clasificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double costoRealizacion {
            get {
                return this.costoRealizacionField;
            }
            set {
                this.costoRealizacionField = value;
                this.RaisePropertyChanged("costoRealizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRealizacion {
            get {
                return this.fechaRealizacionField;
            }
            set {
                this.fechaRealizacionField = value;
                this.RaisePropertyChanged("fechaRealizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRealizacionSpecified {
            get {
                return this.fechaRealizacionFieldSpecified;
            }
            set {
                this.fechaRealizacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRealizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
                this.RaisePropertyChanged("idEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool permiteGrabacion {
            get {
                return this.permiteGrabacionField;
            }
            set {
                this.permiteGrabacionField = value;
                this.RaisePropertyChanged("permiteGrabacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool permiteReingreso {
            get {
                return this.permiteReingresoField;
            }
            set {
                this.permiteReingresoField = value;
                this.RaisePropertyChanged("permiteReingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public productora productora {
            get {
                return this.productoraField;
            }
            set {
                this.productoraField = value;
                this.RaisePropertyChanged("productora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoEvento tipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
                this.RaisePropertyChanged("tipoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEventoSpecified {
            get {
                return this.tipoEventoFieldSpecified;
            }
            set {
                this.tipoEventoFieldSpecified = value;
                this.RaisePropertyChanged("tipoEventoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe")]
    public enum tipoEvento {
        
        /// <remarks/>
        OBRA_TEATRAL,
        
        /// <remarks/>
        CONCIERTO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductoras", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodasProductorasRequest {
        
        public listarTodasProductorasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductorasResponse", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodasProductorasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventMasterSoftWA.ServicioWS.productora[] @return;
        
        public listarTodasProductorasResponse() {
        }
        
        public listarTodasProductorasResponse(EventMasterSoftWA.ServicioWS.productora[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoraWSChannel : EventMasterSoftWA.ServicioWS.ProductoraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoraWSClient : System.ServiceModel.ClientBase<EventMasterSoftWA.ServicioWS.ProductoraWS>, EventMasterSoftWA.ServicioWS.ProductoraWS {
        
        public ProductoraWSClient() {
        }
        
        public ProductoraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse EventMasterSoftWA.ServicioWS.ProductoraWS.listarTodasProductoras(EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductoras(request);
        }
        
        public EventMasterSoftWA.ServicioWS.productora[] listarTodasProductoras() {
            EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest inValue = new EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest();
            EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse retVal = ((EventMasterSoftWA.ServicioWS.ProductoraWS)(this)).listarTodasProductoras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse> EventMasterSoftWA.ServicioWS.ProductoraWS.listarTodasProductorasAsync(EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductorasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarTodasProductorasResponse> listarTodasProductorasAsync() {
            EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest inValue = new EventMasterSoftWA.ServicioWS.listarTodasProductorasRequest();
            return ((EventMasterSoftWA.ServicioWS.ProductoraWS)(this)).listarTodasProductorasAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", ConfigurationName="ServicioWS.EventoWS")]
    public interface EventoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/insertarEventoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/insertarEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventMasterSoftWA.ServicioWS.insertarEventoResponse insertarEvento(EventMasterSoftWA.ServicioWS.insertarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/insertarEventoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/insertarEventoResponse")]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.insertarEventoResponse> insertarEventoAsync(EventMasterSoftWA.ServicioWS.insertarEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/obtenerEventoPorIdRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/obtenerEventoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse obtenerEventoPorId(EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/obtenerEventoPorIdRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/obtenerEventoPorIdResponse")]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse> obtenerEventoPorIdAsync(EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/listarEventosPorNombreReques" +
            "t", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/listarEventosPorNombreRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse listarEventosPorNombre(EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/EventoWS/listarEventosPorNombreReques" +
            "t", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/EventoWS/listarEventosPorNombreRespon" +
            "se")]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEvento", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventMasterSoftWA.ServicioWS.evento evento;
        
        public insertarEventoRequest() {
        }
        
        public insertarEventoRequest(EventMasterSoftWA.ServicioWS.evento evento) {
            this.evento = evento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoResponse", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEventoResponse() {
        }
        
        public insertarEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEventoPorId", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerEventoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public obtenerEventoPorIdRequest() {
        }
        
        public obtenerEventoPorIdRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEventoPorIdResponse", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerEventoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventMasterSoftWA.ServicioWS.evento @return;
        
        public obtenerEventoPorIdResponse() {
        }
        
        public obtenerEventoPorIdResponse(EventMasterSoftWA.ServicioWS.evento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombre", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarEventosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEventosPorNombreRequest() {
        }
        
        public listarEventosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombreResponse", WrapperNamespace="http://services.eventmastersoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarEventosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventMasterSoftWA.ServicioWS.evento[] @return;
        
        public listarEventosPorNombreResponse() {
        }
        
        public listarEventosPorNombreResponse(EventMasterSoftWA.ServicioWS.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventoWSChannel : EventMasterSoftWA.ServicioWS.EventoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoWSClient : System.ServiceModel.ClientBase<EventMasterSoftWA.ServicioWS.EventoWS>, EventMasterSoftWA.ServicioWS.EventoWS {
        
        public EventoWSClient() {
        }
        
        public EventoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventMasterSoftWA.ServicioWS.insertarEventoResponse EventMasterSoftWA.ServicioWS.EventoWS.insertarEvento(EventMasterSoftWA.ServicioWS.insertarEventoRequest request) {
            return base.Channel.insertarEvento(request);
        }
        
        public int insertarEvento(EventMasterSoftWA.ServicioWS.evento evento) {
            EventMasterSoftWA.ServicioWS.insertarEventoRequest inValue = new EventMasterSoftWA.ServicioWS.insertarEventoRequest();
            inValue.evento = evento;
            EventMasterSoftWA.ServicioWS.insertarEventoResponse retVal = ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).insertarEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.insertarEventoResponse> EventMasterSoftWA.ServicioWS.EventoWS.insertarEventoAsync(EventMasterSoftWA.ServicioWS.insertarEventoRequest request) {
            return base.Channel.insertarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.insertarEventoResponse> insertarEventoAsync(EventMasterSoftWA.ServicioWS.evento evento) {
            EventMasterSoftWA.ServicioWS.insertarEventoRequest inValue = new EventMasterSoftWA.ServicioWS.insertarEventoRequest();
            inValue.evento = evento;
            return ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).insertarEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse EventMasterSoftWA.ServicioWS.EventoWS.obtenerEventoPorId(EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest request) {
            return base.Channel.obtenerEventoPorId(request);
        }
        
        public EventMasterSoftWA.ServicioWS.evento obtenerEventoPorId(int idEvento) {
            EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest inValue = new EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest();
            inValue.idEvento = idEvento;
            EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse retVal = ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).obtenerEventoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse> EventMasterSoftWA.ServicioWS.EventoWS.obtenerEventoPorIdAsync(EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest request) {
            return base.Channel.obtenerEventoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.obtenerEventoPorIdResponse> obtenerEventoPorIdAsync(int idEvento) {
            EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest inValue = new EventMasterSoftWA.ServicioWS.obtenerEventoPorIdRequest();
            inValue.idEvento = idEvento;
            return ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).obtenerEventoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse EventMasterSoftWA.ServicioWS.EventoWS.listarEventosPorNombre(EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombre(request);
        }
        
        public EventMasterSoftWA.ServicioWS.evento[] listarEventosPorNombre(string nombre) {
            EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest inValue = new EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse retVal = ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).listarEventosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse> EventMasterSoftWA.ServicioWS.EventoWS.listarEventosPorNombreAsync(EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventMasterSoftWA.ServicioWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(string nombre) {
            EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest inValue = new EventMasterSoftWA.ServicioWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            return ((EventMasterSoftWA.ServicioWS.EventoWS)(this)).listarEventosPorNombreAsync(inValue);
        }
    }
}
